// Generated by gencpp from file mandatory_2/Kalman_feedback_array.msg
// DO NOT EDIT!


#ifndef MANDATORY_2_MESSAGE_KALMAN_FEEDBACK_ARRAY_H
#define MANDATORY_2_MESSAGE_KALMAN_FEEDBACK_ARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mandatory_2/Kalman_feedback.h>

namespace mandatory_2
{
template <class ContainerAllocator>
struct Kalman_feedback_array_
{
  typedef Kalman_feedback_array_<ContainerAllocator> Type;

  Kalman_feedback_array_()
    : array()  {
    }
  Kalman_feedback_array_(const ContainerAllocator& _alloc)
    : array(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::mandatory_2::Kalman_feedback_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >::other >  _array_type;
  _array_type array;





  typedef boost::shared_ptr< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> const> ConstPtr;

}; // struct Kalman_feedback_array_

typedef ::mandatory_2::Kalman_feedback_array_<std::allocator<void> > Kalman_feedback_array;

typedef boost::shared_ptr< ::mandatory_2::Kalman_feedback_array > Kalman_feedback_arrayPtr;
typedef boost::shared_ptr< ::mandatory_2::Kalman_feedback_array const> Kalman_feedback_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mandatory_2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mandatory_2': ['/home/chris/school/ros_catkin/src/mandatory_2/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed7afbae90a21a5359fcd29805b47f62";
  }

  static const char* value(const ::mandatory_2::Kalman_feedback_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed7afbae90a21a53ULL;
  static const uint64_t static_value2 = 0x59fcd29805b47f62ULL;
};

template<class ContainerAllocator>
struct DataType< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mandatory_2/Kalman_feedback_array";
  }

  static const char* value(const ::mandatory_2::Kalman_feedback_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Kalman_feedback[] array\n"
"\n"
"================================================================================\n"
"MSG: mandatory_2/Kalman_feedback\n"
"int16 x\n"
"int16 y\n"
"int8 id\n"
"int16 speed\n"
"\n"
;
  }

  static const char* value(const ::mandatory_2::Kalman_feedback_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Kalman_feedback_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mandatory_2::Kalman_feedback_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mandatory_2::Kalman_feedback_array_<ContainerAllocator>& v)
  {
    s << indent << "array[]" << std::endl;
    for (size_t i = 0; i < v.array.size(); ++i)
    {
      s << indent << "  array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >::stream(s, indent + "    ", v.array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANDATORY_2_MESSAGE_KALMAN_FEEDBACK_ARRAY_H
