// Generated by gencpp from file mandatory_2/Kalman_feedback.msg
// DO NOT EDIT!


#ifndef MANDATORY_2_MESSAGE_KALMAN_FEEDBACK_H
#define MANDATORY_2_MESSAGE_KALMAN_FEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mandatory_2
{
template <class ContainerAllocator>
struct Kalman_feedback_
{
  typedef Kalman_feedback_<ContainerAllocator> Type;

  Kalman_feedback_()
    : x(0)
    , y(0)
    , id(0)
    , speed(0)  {
    }
  Kalman_feedback_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , id(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef int8_t _id_type;
  _id_type id;

   typedef int16_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::mandatory_2::Kalman_feedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mandatory_2::Kalman_feedback_<ContainerAllocator> const> ConstPtr;

}; // struct Kalman_feedback_

typedef ::mandatory_2::Kalman_feedback_<std::allocator<void> > Kalman_feedback;

typedef boost::shared_ptr< ::mandatory_2::Kalman_feedback > Kalman_feedbackPtr;
typedef boost::shared_ptr< ::mandatory_2::Kalman_feedback const> Kalman_feedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mandatory_2::Kalman_feedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mandatory_2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mandatory_2': ['/home/chris/school/ros_catkin/src/mandatory_2/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mandatory_2::Kalman_feedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mandatory_2::Kalman_feedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mandatory_2::Kalman_feedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49283b50500ddc4282cff6ac44c9ef0d";
  }

  static const char* value(const ::mandatory_2::Kalman_feedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49283b50500ddc42ULL;
  static const uint64_t static_value2 = 0x82cff6ac44c9ef0dULL;
};

template<class ContainerAllocator>
struct DataType< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mandatory_2/Kalman_feedback";
  }

  static const char* value(const ::mandatory_2::Kalman_feedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n"
"int16 y\n"
"int8 id\n"
"int16 speed\n"
"\n"
;
  }

  static const char* value(const ::mandatory_2::Kalman_feedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.id);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Kalman_feedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mandatory_2::Kalman_feedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mandatory_2::Kalman_feedback_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANDATORY_2_MESSAGE_KALMAN_FEEDBACK_H
